version: '3'

services:
    example-cloudrun-compose:
        image: gcr.io/cloudrun/hello
        # command: bash
        # labels:
        #     - traefik.enable=true
        #     - 'traefik.frontend.rule=Host:graphql.instabotnet.club'
        expose: 
            - 8080
        ports:
            - 8080:8080
        environment:
            URL_0: 'http://mongoke/'
            URL_1: 'http://server'
    # test:
    #     image: busybox
    #     command: 
    #         - sh
    #         - '-c'
    #         - 'echo ciao'
    # build:
    #     build: .
    #     image: loudrun-compose_build:ciao

    